# 実行ファイル名
TARGET_FILE = ZMUSIC.X

# *.c ソースファイル
C_SRCS = main.c

# ヘッダ検索パス
INCLUDE_FLAGS = -I../ -I../../Zm302_l/

# *.s ソースファイル
ASM_SRCS = 

# リンク対象のライブラリファイル
LIBS = ../../Zm302_l/ZMSC3LIB.L

include ../makefile