# 実行ファイル名
EXECUTABLE = XSPMETA.X

# *.c ソースファイル
C_SRCS = main.c

# ヘッダ検索パス
INCLUDE_FLAGS = -I../ -I../../x68k_xsp/XSP/ -I../../x68k_xsp/PCG90/ -I../../x68k_xsp/PCM8Afnc/

# *.s ソースファイル
#ASM_SRCS = 

# リンク対象のライブラリファイル
LIBS = \
	../../x68k_xsp/XSP/XSP2lib.o \
	../../x68k_xsp/PCG90/PCG90.o \
	../../x68k_xsp/PCM8Afnc/PCM8Afnc.o \

include ../makefile